# Generated by Django 4.1.7 on 2023-03-31 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='status',
            new_name='status_exact',
        ),
    ]
