# Generated by Django 4.1.7 on 2023-03-31 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_status_bookinstance_status_exact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='status_exact',
            new_name='status',
        ),
    ]
