# Generated by Django 4.1.7 on 2023-04-11 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique id for this particular author across the library', primary_key=True, serialize=False),
        ),
    ]
